import{S as E,b as $}from"./assets/vendor-79407357.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const p="b210b8c265aa45ab35b8876089232222",j="eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiMjEwYjhjMjY1YWE0NWFiMzViODg3NjA4OTIzMjIyMiIsInN1YiI6IjY2M2JjY2JlYmRjMjJhNDAxNjAxMDk3NCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.zjkAl594EP84PYZFIQ6iSotECJtDLEMUn35DsNJdj60",b={method:"GET",headers:{accept:"application/json",Authorization:`Bearer ${j}`}},h="https://api.themoviedb.org/3";async function M(t,r){const a=new URLSearchParams({api_key:p,include_adult:!1,language:"en-US",page:r,query:t});return(await fetch(`${h}/search/movie?${a}`,b)).json()}async function P(t){const r=new URLSearchParams({api_key:p,language:"en-US"});return(await fetch(`${h}/movie/${t}?${r}`,b)).json()}async function x(){const t=new URLSearchParams({api_key:p,language:"en-US",page:1});return(await fetch(`${h}/movie/popular?${t}`,b)).json()}async function _(t){const r=new URLSearchParams({api_key:p,language:"en-US"});return(await fetch(`${h}/movie/${t}/videos?${r}`,b)).json()}T();let c=1;const q=document.querySelector(".header-search");q.addEventListener("submit",v);const f=document.querySelector(".library-prev-btn"),g=document.querySelector(".library-next-btn");f.addEventListener("click",I);g.addEventListener("click",N);function I(){const t=document.querySelector(".library-page");c--,v(event),t.textContent=c,window.scrollTo({top:0,behavior:"smooth"})}function N(){const t=document.querySelector(".library-page");c++,v(event),t.textContent=c,window.scrollTo({top:0,behavior:"smooth"})}async function v(t){t.preventDefault();const r=q.querySelector(".header-search-input"),a=document.querySelector(".library-list"),s=document.querySelector(".library-loader"),e=document.querySelector(".library-message"),o=document.querySelector(".library-title"),n=document.querySelector(".library-pagination");s.classList.remove("hide"),a.innerHTML="";try{const i=await M(r.value.trim(),c);if(o.innerHTML=`Search query: <span>${r.value.trim()}</span>`,!i.results.length)e.classList.add("active"),n.classList.remove("active");else{e.classList.remove("active");const u=i.results.map(({id:L,title:m,overview:S,release_date:y,vote_average:l,poster_path:w})=>w?`
        <li class="library-item">
          <img src="https://image.tmdb.org/t/p/w500/${w}" alt="${m}" class="library-item-poster" />
          <div class="library-item-content">
            <h3 class="library-item-title">${m}</h3>
            <p class="library-item-date library-item-text">Release date: <span>${y}</span></p>
            <p class="library-item-rate library-item-text">Rating: <span>${l}</span></p>
            <button type="button" class="library-item-btn" data-id="${L}">Read more</button>
          </div>
        </li>
      `:"").join("");a.insertAdjacentHTML("beforeend",u),n.classList.add("active");const d=i.total_pages;c>=d?g.disabled=!0:g.disabled=!1,c<=1?f.disabled=!0:f.disabled=!1}}catch(i){console.log(i)}finally{s.classList.add("hide")}}async function T(){const t=document.querySelector(".library-list"),r=document.querySelector(".library-loader");t.innerHTML="",r.classList.remove("hide");try{const s=(await x()).results.map(({id:e,title:o,overview:n,release_date:i,vote_average:u,poster_path:d})=>d?`
        <li class="library-item">
          <img src="https://image.tmdb.org/t/p/w500/${d}" alt="${o}" class="library-item-poster" />
          <div class="library-item-content">
            <h3 class="library-item-title">${o}</h3>
            <p class="library-item-date library-item-text">Release date: <span>${i}</span></p>
            <p class="library-item-rate library-item-text">Rating: <span>${u}</span></p>
            <button type="button" class="library-item-btn" data-id="${e}">Read more</button>
          </div>
        </li>
      `:"").join("");t.insertAdjacentHTML("beforeend",s)}catch(a){console.log(a)}finally{r.classList.add("hide")}}const C=document.querySelector(".library-list"),J=document.querySelector(".modal-close-btn");J.addEventListener("click",t=>{t.target.closest(".backdrop").classList.remove("active"),document.body.style.overflow=null});C.addEventListener("click",O);async function O(t){if(t.target.classList.contains("library-item-btn")){const r=t.target.dataset.id,a=document.querySelector(".modal-loader"),s=document.querySelector(".modal");a.classList.remove("hide");try{const e=await P(r),{id:o,poster_path:n,title:i,status:u,release_date:d,genres:L,vote_average:m,overview:S}=e,y=s.querySelector(".modal-video-btn"),l={img:s.querySelector(".modal-img"),title:s.querySelector(".modal-title"),status:s.querySelector(".modal-status span"),release:s.querySelector(".modal-released span"),rating:s.querySelector(".modal-rating span"),descr:s.querySelector(".modal-descr")};l.img.src=`https://image.tmdb.org/t/p/w500/${n}`,l.img.alt=i,l.title.textContent=i,l.status.textContent=u,l.release.textContent=d,l.rating.textContent=m,l.descr.textContent=S,y.dataset.id=o,s.classList.add("active"),document.body.style.overflow="hidden",y.addEventListener("click",R)}catch(e){console.log(e)}finally{a.classList.add("hide")}}}async function R(t){const r=t.currentTarget.dataset.id;try{const a=await _(r);if(!a.results.length)E.fire({icon:"error",title:"Oops...",text:"We couldn't find the trailer for this movie"});else{const s=a.results[0].key;$.create(`
    <iframe src="https://www.youtube.com/embed/${s}" width="800" height="500" frameborder="0"></iframe>
  `).show()}}catch(a){console.log(a)}}
//# sourceMappingURL=commonHelpers.js.map
