import{S as E,b as $}from"./assets/vendor-79407357.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const p="b210b8c265aa45ab35b8876089232222",j="eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiMjEwYjhjMjY1YWE0NWFiMzViODg3NjA4OTIzMjIyMiIsInN1YiI6IjY2M2JjY2JlYmRjMjJhNDAxNjAxMDk3NCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.zjkAl594EP84PYZFIQ6iSotECJtDLEMUn35DsNJdj60",b={method:"GET",headers:{accept:"application/json",Authorization:`Bearer ${j}`}},h="https://api.themoviedb.org/3";async function M(e,r){const a=new URLSearchParams({api_key:p,include_adult:!1,language:"en-US",page:r,query:e});return(await fetch(`${h}/search/movie?${a}`,b)).json()}async function x(e){const r=new URLSearchParams({api_key:p,language:"en-US"});return(await fetch(`${h}/movie/${e}?${r}`,b)).json()}async function P(){const e=new URLSearchParams({api_key:p,language:"en-US",page:1});return(await fetch(`${h}/movie/popular?${e}`,b)).json()}async function _(e){const r=new URLSearchParams({api_key:p,language:"en-US"});return(await fetch(`${h}/movie/${e}/videos?${r}`,b)).json()}N();let c=1;const q=document.querySelector(".header-search");q.addEventListener("submit",e=>{const r=document.querySelector(".library-page");c=1,r.textContent=c,v(e)});const f=document.querySelector(".library-prev-btn"),g=document.querySelector(".library-next-btn");f.addEventListener("click",I);g.addEventListener("click",C);function I(){const e=document.querySelector(".library-page");c--,v(event),e.textContent=c,window.scrollTo({top:0,behavior:"smooth"})}function C(){const e=document.querySelector(".library-page");c++,v(event),e.textContent=c,window.scrollTo({top:0,behavior:"smooth"})}async function v(e){e.preventDefault();const r=q.querySelector(".header-search-input"),a=document.querySelector(".library-list"),s=document.querySelector(".library-loader"),t=document.querySelector(".library-message"),o=document.querySelector(".library-title"),i=document.querySelector(".library-pagination");s.classList.remove("hide"),a.innerHTML="";try{const n=await M(r.value.trim(),c);if(o.innerHTML=`Search query: <span>${r.value.trim()}</span>`,!n.results.length)t.classList.add("active"),i.classList.remove("active");else{t.classList.remove("active");const u=n.results.map(({id:S,title:m,overview:L,release_date:y,vote_average:l,poster_path:w})=>w?`
          <li class="library-item">
          <img src="https://image.tmdb.org/t/p/w500/${w}" alt="${m}" class="library-item-poster" />
          <div class="library-item-content">
          <h3 class="library-item-title">${m}</h3>
          <p class="library-item-date library-item-text">Release date: <span>${y}</span></p>
          <p class="library-item-rate library-item-text">Rating: <span>${l}</span></p>
          <button type="button" class="library-item-btn" data-id="${S}">Read more</button>
          </div>
          </li>
          `:"").join("");a.insertAdjacentHTML("beforeend",u),i.classList.add("active");const d=n.total_pages;c>=d?g.disabled=!0:g.disabled=!1,c<=1?f.disabled=!0:f.disabled=!1}}catch(n){console.log(n)}finally{s.classList.add("hide")}}async function N(){const e=document.querySelector(".library-list"),r=document.querySelector(".library-loader");e.innerHTML="",r.classList.remove("hide");try{const s=(await P()).results.map(({id:t,title:o,overview:i,release_date:n,vote_average:u,poster_path:d})=>d?`
        <li class="library-item">
          <img src="https://image.tmdb.org/t/p/w500/${d}" alt="${o}" class="library-item-poster" />
          <div class="library-item-content">
            <h3 class="library-item-title">${o}</h3>
            <p class="library-item-date library-item-text">Release date: <span>${n}</span></p>
            <p class="library-item-rate library-item-text">Rating: <span>${u}</span></p>
            <button type="button" class="library-item-btn" data-id="${t}">Read more</button>
          </div>
        </li>
      `:"").join("");e.insertAdjacentHTML("beforeend",s)}catch(a){console.log(a)}finally{r.classList.add("hide")}}const T=document.querySelector(".library-list"),J=document.querySelector(".modal-close-btn");J.addEventListener("click",e=>{e.target.closest(".backdrop").classList.remove("active"),document.body.style.overflow=null});T.addEventListener("click",O);async function O(e){if(e.target.classList.contains("library-item-btn")){const r=e.target.dataset.id,a=document.querySelector(".modal-loader"),s=document.querySelector(".modal");a.classList.remove("hide");try{const t=await x(r),{id:o,poster_path:i,title:n,status:u,release_date:d,genres:S,vote_average:m,overview:L}=t,y=s.querySelector(".modal-video-btn"),l={img:s.querySelector(".modal-img"),title:s.querySelector(".modal-title"),status:s.querySelector(".modal-status span"),release:s.querySelector(".modal-released span"),rating:s.querySelector(".modal-rating span"),descr:s.querySelector(".modal-descr")};l.img.src=`https://image.tmdb.org/t/p/w500/${i}`,l.img.alt=n,l.title.textContent=n,l.status.textContent=u,l.release.textContent=d,l.rating.textContent=m,l.descr.textContent=L,y.dataset.id=o,s.classList.add("active"),document.body.style.overflow="hidden",y.addEventListener("click",R)}catch(t){console.log(t)}finally{a.classList.add("hide")}}}async function R(e){const r=e.currentTarget.dataset.id;try{const a=await _(r);if(!a.results.length)E.fire({icon:"error",title:"Oops...",text:"We couldn't find the trailer for this movie"});else{const s=a.results[0].key;$.create(`
    <iframe src="https://www.youtube.com/embed/${s}" width="800" height="500" frameborder="0"></iframe>
  `).show()}}catch(a){console.log(a)}}
//# sourceMappingURL=commonHelpers.js.map
