(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const p="b210b8c265aa45ab35b8876089232222",m={method:"GET",headers:{accept:"application/json",Authorization:"Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiMjEwYjhjMjY1YWE0NWFiMzViODg3NjA4OTIzMjIyMiIsInN1YiI6IjY2M2JjY2JlYmRjMjJhNDAxNjAxMDk3NCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.zjkAl594EP84PYZFIQ6iSotECJtDLEMUn35DsNJdj60"}};async function f(r){const o="https://api.themoviedb.org/3/search/movie",s=new URLSearchParams({api_key:p,include_adult:!1,language:"en-US",page:1,query:r});return(await fetch(`${o}?${s}`,m)).json()}async function h(r){const o="https://api.themoviedb.org/3/movie",s=new URLSearchParams({language:"en-US"});return(await fetch(`${o}/${r}?${s}`,m)).json()}const g=document.querySelector(".header-search");g.addEventListener("submit",b);async function b(r){r.preventDefault();const o=r.currentTarget.elements.movie,s=document.querySelector(".library-list"),a=document.querySelector(".library-loader");try{const e=await f(o.value.trim());s.innerHTML="",a.classList.remove("hide");const t=e.results.map(({id:n,title:c,overview:y,release_date:d,vote_average:u,poster_path:i})=>i?`
        <li class="library-item">
          <img src="https://image.tmdb.org/t/p/w500/${i}" alt="${c}" class="library-item-poster" />
          <div class="library-item-content">
            <h3 class="library-item-title">${c}</h3>
            <p class="library-item-date library-item-text">Release date: <span>${d}</span></p>
            <p class="library-item-rate library-item-text">Rating: <span>${u}</span></p>
            <button type="button" class="library-item-btn" data-id="${n}">Read more</button>
          </div>
        </li>
      `:"").join("");s.insertAdjacentHTML("beforeend",t),console.log(e)}catch(e){console.log(e)}finally{a.classList.add("hide")}}const v=document.querySelector(".library-list"),L=document.querySelector(".modal-close-btn");L.addEventListener("click",r=>{r.target.closest(".backdrop").classList.remove("active"),document.body.style.overflow=null});v.addEventListener("click",S);async function S(r){if(r.target.classList.contains("library-item-btn")){const o=r.target.dataset.id,s=document.querySelector(".modal-loader");try{const a=await h(o);s.classList.remove("hide");const{poster_path:e,original_title:t,status:n,release_date:c,genres:y,vote_average:d,overview:u}=a,i=document.querySelector(".modal"),l={img:i.querySelector(".modal-img"),title:i.querySelector(".modal-title"),status:i.querySelector(".modal-status span"),release:i.querySelector(".modal-released span"),rating:i.querySelector(".modal-rating span"),descr:i.querySelector(".modal-descr")};l.img.src=`https://image.tmdb.org/t/p/w500/${e}`,l.img.alt=t,l.title.textContent=t,l.status.textContent=n,l.release.textContent=c,l.rating.textContent=d,l.descr.textContent=u,i.classList.add("active"),document.body.style.overflow="hidden"}catch(a){console.log(a)}finally{s.classList.add("hide")}}}
//# sourceMappingURL=commonHelpers.js.map
